config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help', as: 'helf'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/forms', to: 'fillable_forms#index'
  get '/new_form', to: 'fillable_forms#new'
  post '/new_form', to: 'fillable_forms#create'

  resources :users  #endows the app with all the actions needed for a RESTful Users resource, along with a large number of named routes for generating user URLs.

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>  <%# Rails should call the provide function and associate the string "About" with the label :title %>
<h1>About</h1>
<p>This is the about page</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>  <%# Rails should call the provide function and associate the string "Contact" with the label :title %>
<h1>Contact</h1>
<p>
    Contact the developers at the
    <a href="">page</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>   <%# Rails should call the provide function and associate the string "Help" with the label :title %>
<h1>Help</h1>
<p>This is the Help page</p>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>   <%# Rails should call the provide function and associate the string "Home" with the label :title %>
<div class="center jumbotron">
  <h1>Welcome to EduTech</h1>

  <h2>
    This is the home page for the EduTech website
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>   <%# creates a stub link of the form %>
</div>

<%= link_to image_tag("edutech.png", alt: "EduTech logo") %>  <%# app/assets/images %>