config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help', as: 'helf'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/forms', to: 'fillable_forms#index'
  get '/new_form', to: 'fillable_forms#new'
  post '/new_form', to: 'fillable_forms#create'

  resources :users  #endows the app with all the actions needed for a RESTful Users resource, along with a large number of named routes for generating user URLs.

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/fillable_forms_controller.rb
class FillableFormsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @user = current_user
    @forms = @user.fillable_forms.all
  end

  def new
     @fillable_forms = FillableForm.new
  end

  def create
    @fillable_forms = current_user.fillable_forms.create(body: params[:post][:body])
    binding.pry
    if @fillable_forms.save
      redirect_to '/forms'
    else
      render 'new'
    end
  end

  # def show
  #   @fillable_forms = Post.find(params[:id])
  # end

  # def edit
  #   @fillable_forms = Post.find(params[:id])
  # end
  #
  # def update
  #   @fillable_forms = Post.find(params[:id])
  #
  #   if @fillable_forms.update(params[:post].permit(:body))
  #     redirect_to @fillable_forms
  #   else
  #     render 'edit'
  #   end
  # end

  # def destroy
  #   @fillable_forms = Post.find(params[:id])
  #   @fillable_forms.destroy
  #
  #   redirect_to forms_path
  # end

  private
    def fillable_forms_params
      params.require(:post).permit(:body)
    end
end

app/helpers/fillable_forms_helper.rb
module FillableFormsHelper
end

app/views/fillable_forms/_hidden_answers.html.erb
<% %>

app/views/fillable_forms/index.html.erb
<li class="new-form-button"><%= link_to "New Form", new_form_path %></li>
<% @forms.each do |form| %>
  <%= simple_format form.body %>
<% end %>

app/views/fillable_forms/new.html.erb
<% provide(:title, "Fillable Form") %>   <%# Rails should call the provide function and associate the string "Help" with the label :title %>
<h1>Create a new form</h1>
  <%= form_for :post, url: new_form_path do |f| %>
    <% if @fillable_forms.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@fillable_forms.errors.count, "error") %> prevented this post from saving</h2>
      </div>
    <% end %>
    <p>
      <%= f.label :title %>
      <%= f.text_area :title %>
      <%= tinymce_assets %>
      <%= tinymce %>
      <%= f.label :body %><br>
      <%= f.text_area :body, class: "tinymce" %>
    </p>
    <p>
      <a id="tinymceSubmit"><%= f.submit %></a>
    </p>
  <% end %>

app/views/fillable_forms/show.html.erb
<h1 class ="body" >
  <%= @fillable_forms.body %>
</h1>

<p class="data">
  Submitted <%= time_ago_in_words(@fillable_forms.created_at) %> Ago
</p>