config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help', as: 'helf'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/forms', to: 'fillable_forms#index'
  get '/new_form', to: 'fillable_forms#new'
  post '/new_form', to: 'fillable_forms#create'

  resources :users  #endows the app with all the actions needed for a RESTful Users resource, along with a large number of named routes for generating user URLs.

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The EduTech App by Pratiman Shahi, Gregory Markou and Jonathan Ge
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">   <%# header tag indicates elements that should go at the top of the page %>
  <div class="container">
    <%= link_to "EduTech", root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">  <%# list of navigatioon links %>
        <li><%= link_to "Home",   root_path %></li>   <%# uses the Rails helper link_to to create links, the thirs optional argument is an options hash %>
        <li><%= link_to "Help",   helf_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class='divider'></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<%# HTML5 shim or JavaScript code to work around HTML5 not working on older browsers and IE %>
<!--[if lt IE 9]>   <%# conditional comment supported by IE browsers for just this sort of situation %>
  <script src="//cdnjs.cloudfare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>   <%# Rails uses HTML5 by default %>
<html>
  <head>
    <title><%= yield(:title) %> | EduTech </title>  <%# This code is responsible for inserting the contents of each page into the layout %>
    <%= csrf_meta_tags %>   <%# Prevents cross-site request forgery, a type of malicious web attack %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>  <%# uses the built-in stylesheet_link_tag to include application.css for all media types (including computer screens and printers) %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>  <%# inserting partials %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="container">   <%# div tag divides the document into distinct parts, with a CSS class container %>
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: 'alert alert-#{message_tye}') %>
        <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>  <%# display some useful information about each page. Restricted to the development environment %>
    </div>
  </body>
</html>